### ISSUE TITLE
Only first item in samplesheet processed when no db parameter provided 

### ISSUE THREAD

**Issue by JoseEspinosa** [nf-core/proteinfold#144]
### Description of the bug

When running colabfold_webserver and not providing the `--colabfold_db` parameter, see [this](https://nfcore.slack.com/archives/C0351A8S487/p1712248880698989) slack thread or also when running the alphafold mode without providing the `--alphafold_db` parameter

### Command used and terminal output

For colabfold:

$ NXF_VER=23.10.1 nextflow run main.nf -profile docker --outdir results -params-file params.yml -c custom.config

Where params.yml:

```yaml
input: 'samples.csv'
outdir: 'results'
mode: 'colabfold'
colabfold_server: 'webserver'
```

For Alphafold:

```console
NXF_VER=23.10.1 nextflow run main.nf -profile docker --outdir results -params-file params_af2.yml -c custom.config
```

Where `params_af2.yml`:

```yaml
input: 'samples.csv'
outdir: 'results'
mode: 'alphafold2'
alphafold2_mode : 'standard'
```

And custom.config for both:

```
stubRun = true

params {
    config_profile_name        = 'Test profile'
    config_profile_description = 'Minimal test dataset to check pipeline function'

    // Limit resources so that this can run on GitHub Actions
    max_cpus   = 2
    max_memory = '6.GB'
    max_time   = '6.h'
}

process {
    withName: 'ARIA2' {
        container = 'biocontainers/gawk:5.1.0'
    }
    withName: 'UNTAR' {
        container = 'biocontainers/gawk:5.1.0'
    }
    withName: 'COLABFOLD_BATCH' {
        container = 'biocontainers/gawk:5.1.0'
    }
    withName: 'RUN_ALPHAFOLD2' {
        container = 'biocontainers/gawk:5.1.0'
    }
}
```
